import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dumisani | Frontend Developer & Data Analyst',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" sizes="250x250" href="/favicon.png" />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
